version: '3'
services:
  nestjs_app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    # image: backend-planilla
    container_name: back-rrhh
    ports:
      - '${PORT}:3003'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      API_PREFIX: ${API_PREFIX}
      HOST_API: ${HOST_API}

  db:
    image: postgres:16
    container_name: db-planilla
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
